/* ============================================================
   GUESSTIMATE — Fermi estimation question bank (50 questions).
   Each entry: q (the question), answer (the true numeric answer),
   unit (optional display noun), why (the estimation reasoning
   shown on the reveal screen). Price-is-Right rules: closest
   guess WITHOUT going over wins the round.
   ============================================================ */
const GUESSTIMATE_QUESTIONS = [
  { q: "How many piano tuners are there in Chicago?", answer: 50, unit: "tuners",
    why: "Chicago has ~2.7M people → ~20,000 pianos → each tuned yearly → one tuner does ~500 a year → ~40–50 tuners." },
  { q: "How many golf balls fit inside a school bus?", answer: 500000, unit: "golf balls",
    why: "A bus holds ~1,575 cu ft; a golf ball is 2.5 cu in; with packing gaps that's ~450 balls per cu ft → ~500K–700K." },
  { q: "How many bricks are in the Empire State Building?", answer: 10000000, unit: "bricks",
    why: "The famous figure: roughly 10 million bricks in the facade." },
  { q: "How many seconds are in a year?", answer: 31536000, unit: "seconds",
    why: "60 × 60 × 24 × 365 = 31,536,000." },
  { q: "How many times does the human heart beat in an average lifetime?", answer: 2800000000, unit: "beats",
    why: "70 bpm × 60 × 24 × 365 × 75 years ≈ 2.8 billion beats." },
  { q: "How many cups of coffee are drunk in the US every day?", answer: 400000000, unit: "cups",
    why: "~2/3 of American adults drink coffee, about 3 cups each." },
  { q: "How many text messages are sent worldwide every day?", answer: 20000000000, unit: "texts",
    why: "Roughly 20 billion person-to-person texts fly around daily." },
  { q: "How many Google searches happen every day?", answer: 13500000000, unit: "searches",
    why: "~13.5 billion a day — about 5 trillion a year." },
  { q: "How many steps does it take to walk a marathon?", answer: 55000, unit: "steps",
    why: "26.2 miles × 5,280 ft ÷ ~2.5 ft per step ≈ 55,000." },
  { q: "How many calories are in a Big Mac?", answer: 590, unit: "calories",
    why: "Straight off the McDonald's menu board: 590." },
  { q: "How tall is the Eiffel Tower, in feet?", answer: 1083, unit: "feet",
    why: "330 meters ≈ 1,083 ft, antenna included." },
  { q: "How many tons does the Statue of Liberty weigh?", answer: 225, unit: "tons",
    why: "Copper skin + iron frame ≈ 225 tons." },
  { q: "How many Lego bricks have ever been made?", answer: 600000000000, unit: "bricks",
    why: "Lego says over 600 billion bricks and counting." },
  { q: "How many words are in all 7 Harry Potter books combined?", answer: 1080000, unit: "words",
    why: "All seven books total ~1.08 million words." },
  { q: "How many episodes of The Simpsons have aired?", answer: 790, unit: "episodes",
    why: "36+ seasons and still going." },
  { q: "How many miles long is the Great Wall of China?", answer: 13171, unit: "miles",
    why: "All branches measured end to end: ~13,171 miles." },
  { q: "How deep is the Mariana Trench, in feet?", answer: 36000, unit: "feet",
    why: "About 36,000 ft deep — Mount Everest would fit with room to spare." },
  { q: "How fast is a sneeze, in mph?", answer: 100, unit: "mph",
    why: "~100 mph. Cover your nose." },
  { q: "What is the world record for hot dogs eaten in 10 minutes?", answer: 76, unit: "hot dogs",
    why: "Joey Chestnut, 2021 — 76 dogs and buns." },
  { q: "How many people have walked on the Moon?", answer: 12, unit: "people",
    why: "All Apollo missions, 1969–1972: twelve moonwalkers." },
  { q: "How many stars are in the Milky Way?", answer: 100000000000, unit: "stars",
    why: "Estimates range from 100 to 400 billion stars." },
  { q: "How many rolls of toilet paper does the average American use per year?", answer: 100, unit: "rolls",
    why: "About 20,000 sheets a year per person." },
  { q: "How many gallons of water does it take to make one pair of jeans?", answer: 1800, unit: "gallons",
    why: "Growing the cotton is the thirsty part: ~1,800 gallons." },
  { q: "How many McDonald's restaurants are there worldwide?", answer: 43000, unit: "restaurants",
    why: "40,000+ restaurants across 100+ countries." },
  { q: "How many iPhones are sold per year?", answer: 230000000, unit: "iPhones",
    why: "Apple moves roughly 230 million iPhones in a peak year." },
  { q: "How many emails are sent worldwide every day?", answer: 350000000000, unit: "emails",
    why: "~350 billion emails a day — most of it spam." },
  { q: "How many hours of video are uploaded to YouTube every minute?", answer: 500, unit: "hours",
    why: "500 hours every minute — you could never catch up." },
  { q: "How many words does the average person speak per day?", answer: 16000, unit: "words",
    why: "Roughly 16,000 words come out of the average mouth daily." },
  { q: "How many times do you breathe per day?", answer: 20000, unit: "breaths",
    why: "~16 breaths per minute × 1,440 minutes ≈ 20,000+." },
  { q: "How many bones are in the adult human body?", answer: 206, unit: "bones",
    why: "Babies start with ~300; they fuse into 206." },
  { q: "How many taste buds are on the human tongue?", answer: 10000, unit: "taste buds",
    why: "~10,000 taste buds, replaced every couple of weeks." },
  { q: "How many miles wide is the Earth?", answer: 7918, unit: "miles",
    why: "Earth's diameter ≈ 7,918 miles." },
  { q: "How many miles away is the Moon?", answer: 239000, unit: "miles",
    why: "~238,855 miles on average — it varies by ~30,000." },
  { q: "How many dimples are on a standard golf ball?", answer: 336, unit: "dimples",
    why: "Most balls have 300–500 dimples; 336 is the classic count." },
  { q: "How many people live in New York City?", answer: 8300000, unit: "people",
    why: "~8.3 million people across the five boroughs." },
  { q: "How many subway stations does NYC have?", answer: 472, unit: "stations",
    why: "472 stations — more than any other system in the world." },
  { q: "How many slices of pizza are eaten per second in the US?", answer: 350, unit: "slices",
    why: "~350 slices every single second." },
  { q: "How many burgers has McDonald's served, per its famous signs?", answer: 99000000000, unit: "burgers",
    why: "The signs famously stopped counting at 'Over 99 Billion Served'." },
  { q: "How many windows are in the Empire State Building?", answer: 6514, unit: "windows",
    why: "6,514 windows to wash." },
  { q: "How many floors does the Empire State Building have?", answer: 102, unit: "floors",
    why: "102 floors, completed in 1931." },
  { q: "How many years would it take to count to one billion, one number per second?", answer: 32, unit: "years",
    why: "31.7 years — and that's without sleeping." },
  { q: "How many times would you have to fold a paper to reach the Moon?", answer: 42, unit: "folds",
    why: "Doubling the thickness 42 times gets you past 238,855 miles." },
  { q: "How many squares are on a chessboard, counting all sizes?", answer: 204, unit: "squares",
    why: "64 + 49 + 36 + 25 + 16 + 9 + 4 + 1 = 204." },
  { q: "How many keys are on a standard piano?", answer: 88, unit: "keys",
    why: "52 white keys, 36 black keys." },
  { q: "How many tiles are in an English Scrabble set?", answer: 100, unit: "tiles",
    why: "100 tiles — two of them blank." },
  { q: "How many gallons of water are in an Olympic swimming pool?", answer: 660000, unit: "gallons",
    why: "~660,000 gallons in a 50-meter pool." },
  { q: "How many miles long is the Nile River?", answer: 4130, unit: "miles",
    why: "~4,130 miles — it fights the Amazon for the longest-river title." },
  { q: "How many countries are in the world?", answer: 195, unit: "countries",
    why: "193 UN members + 2 observer states." },
  { q: "How many hairs are on the average human head?", answer: 100000, unit: "hairs",
    why: "~100,000 hairs (redheads fewer, blondes more)." },
  { q: "How many miles of blood vessels are in the human body?", answer: 60000, unit: "miles",
    why: "~60,000 miles — enough to circle the Earth twice." },
];
